#!/bin/bash
#
# 概要:
# Travis CI で利用するスクリプト
#
# テスト流れ:
# テストはビルドが成功するかどうかを見る（check 関数までの実行）
# すべてのパッケージ（`master`に含まれるバージョン）が通ったら bekobrew-packages
# リポジトリのテストが通ったことにする
# 通ったパッケージの一覧は何らかのブランチ(`misc` とか？)に記録しておく
#
# テストを通ったパッケージリスト:
# `misc` ブランチ
# ファイル名: good_package_list
# {バージョン文字列を含むパッケージ名} のリスト
# このファイルに、masterブランチに含まれるBEKOBUILDファイルの情報が
# すべて含まれていればテストを通ったことにする

source ./lib/utils.sh

for package_name in `get_tested_package_names`; do
  echo "Testing: ${package_name}"
  run_test ${package_name}
done

